In [1]:
print("Hello world of python ...!!!")

Hello world of python ...!!!


In [29]:
#1
def divi(a):
    try:
        5/a
    except Exception as e:
        print(e)
    else:
        return 5/a
    finally:
        print("done suceessfully !!")
        

In [30]:
divi(0)

division by zero
done suceessfully !!


In [31]:
divi(2)

done suceessfully !!


2.5

In [28]:
#2
subjects=["Americans","Indians"]
verbs=["play", "watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k+".")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [35]:
[i+" "+j+" "+k for i in subjects for j in verbs for k in objects]

['Americans play Baseball',
 'Americans play Cricket',
 'Americans watch Baseball',
 'Americans watch Cricket',
 'Indians play Baseball',
 'Indians play Cricket',
 'Indians watch Baseball',
 'Indians watch Cricket']

In [1]:
import numpy as np

In [43]:
x=np.array([1,2,3,5])

n=3

a=np.column_stack([x**(n-i-1) for i in range(n)])

a



array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [44]:
#Task-2


def matrix(option,n):
    x=np.array([1,2,3,4])
    if(option==False):
        v=np.column_stack([x**(n-1-i) for i in range(n)])
        print(v)
    if(option==True):
        v=np.vander(x,n,increasing=True)
        print(v)
   

In [45]:
matrix(True,3)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [46]:
matrix(False,3)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
